version: "3.8"

services:
  hadoop-master:
    image: yassern1/hadoop-spark-jupyter:1.0.3
    container_name: hadoop-master
    hostname: hadoop-master
    ports:
      - "9870:9870"   # HDFS NameNode UI
      - "8088:8088"   # YARN ResourceManager UI
      - "7077:7077"   # Spark master
      - "19888:19888" # MapReduce JobHistory
      - "8080:8080"   # Jupyter / autres services
      - "9000:9000"   # HDFS NameNode RPC
    volumes:
      # ⚠️ adapte le chemin si ton utilisateur Windows n'est pas "pc"
      - "C:/Users/pc/Documents/hadoop_project:/shared_volume"
    networks:
      - hadoop

  hadoop-slave1:
    image: yassern1/hadoop-spark-jupyter:1.0.3
    container_name: hadoop-slave1
    hostname: hadoop-slave1
    ports:
      - "8040:8042"   # NodeManager 1
    networks:
      - hadoop

  hadoop-slave2:
    image: yassern1/hadoop-spark-jupyter:1.0.3
    container_name: hadoop-slave2
    hostname: hadoop-slave2
    ports:
      - "8041:8042"   # NodeManager 2
    networks:
      - hadoop

networks:
  hadoop:
    driver: bridge
